import { GeistSans } from 'geist/font/sans';
import type { Metadata } from "next";
import { } from "next/font/google";
import { Toaster } from 'sonner';
import "../styles/index.css";
import "./globals.css";
import AppProvider from '@/context/app-context';
import SlideSession from '@/components/common/slide-session';

// const geistSans = GeistSans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MangaHub",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Toaster richColors position="top-right" />
        <AppProvider >
          <SlideSession />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
